=== salvatiti/2-DAW/XML/Juan Pardo/pardo.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,nacimiento?,direccion+,(varon|hembra))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ELEMENT direccion (calle,poblacion,provincia,cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT varon EMPTY>
<!ELEMENT hembra EMPTY>

<!ATTLIST nacimiento dia CDATA #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento aÃ±o CDATA #REQUIRED>

=== salvatiti/2-DAW/XML/Juan Pardo/pardo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "pardo.dtd">
<personas>
<persona>
<nombre>Juan Pardo</nombre>
<nacimiento dia = "10" mes = "Abril" año="1982" />
<direccion>
<calle>Caoba,1</calle>
<poblacion>Madrid</poblacion>
<provincia>Madrid</provincia>
<cp>20040</cp>
</direccion>
<varon/>
</persona>

<persona>
<nombre>Juana Parda</nombre>
<nacimiento dia = "11" mes = "Abril" año="1982" />
<direccion>
<calle>Caoba,2</calle>
<poblacion>Madrid</poblacion>
<provincia>Madrid</provincia>
<cp>20040</cp>
</direccion>
<hembra/>
</persona>

</personas>
