=== salvatiti/2-DAW/XML/SCHEMA/modelos/modelos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:simpleType name="tiponombre">
<xs:restriction base="xs:string">

<xs:pattern value ="Barbara|Lily|Behati|Francisco"/>

</xs:restriction>
</xs:simpleType>

    <xs:element name="nombre" type="tiponombre" />
    <xs:element name="apellidos" type="xs:string" />
    <xs:element name="edad" type="xs:integer" />
    <xs:element name="nacionalidad" type="xs:string" />
    <xs:element name="marca" type="xs:string" />
    <xs:element name="hombre" />
    <xs:element name="mujer" />


    <xs:attribute name=" altura" type="xs:float" />
    <xs:attribute name=" peso" type="xs:integer" />


    <xs:element name="modelos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="modelo" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="apellidos" />
                <xs:element ref="edad" />
                <xs:element ref="nacionalidad" />
                <xs:element ref="desfiles" minOccurs="0" />
                <xs:choice>
                    <xs:element ref="hombre" />
                    <xs:element ref="mujer" />
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="altura" />
            <xs:attribute ref="peso" />
        </xs:complexType>
    </xs:element>


    <xs:element name="desfiles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="marca" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== salvatiti/2-DAW/XML/SCHEMA/modelos/modelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<modelos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modelos.xsd">

<modelo altura="1.71" peso="51">
<nombre>Barbara</nombre>
<apellidos>Palvin</apellidos>
<edad>19</edad>
<nacionalidad>Hungria</nacionalidad>
<desfiles>
<marca>Armani</marca>
<marca>Pull and Bear</marca>
</desfiles>
<mujer/>
</modelo>

<modelo altura="1.75" peso="55">
<nombre>Lily</nombre>
<apellidos>Aldrige</apellidos>
<edad>30</edad>
<nacionalidad>Estados Unidos</nacionalidad>
<mujer/>
</modelo>

<modelo altura="1.78" peso="51">
<nombre>Behati</nombre>
<apellidos>Prinsloo</apellidos>
<edad>26</edad>
<nacionalidad>Namibia</nacionalidad>
<desfiles>
<marca>Hugo Boss</marca>
<marca>Chanel</marca>
<marca>DKNY</marca>
</desfiles>
<mujer/>
</modelo>

<modelo altura="1.86" peso="73">
<nombre>Francisco</nombre>
<apellidos>Lachowski</apellidos>
<edad>24</edad>
<nacionalidad>Brasil</nacionalidad>
<desfiles>
<marca>Karl Lagerfeld</marca>
<marca>Dior Homme</marca>
<marca>Ermenegildo Zegna</marca>
<marca>Lacoste</marca>
</desfiles>
<hombre/>
</modelo>


</modelos>
