=== salvatiti/2-DAW/XML/Videoclub/videoclub.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT facturas (factura+)>
<!ELEMENT factura (datos_cliente,datos_factura)>
<!ELEMENT datos_cliente (nombre,apellido+,dni,tfno?)>
<!ATTLIST datos_cliente ident ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT tfno (#PCDATA)>

<!ELEMENT datos_factura (resguardo,(alquileres | compras | (alquileres,compras)))>
<!ELEMENT resguardo (forma_pago,importe_total)>
<!ELEMENT forma_pago (#PCDATA)>
<!ELEMENT importe_total (#PCDATA)>
<!ELEMENT alquileres (fecha,peliculas)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo,genero,duracion,actores)>
<!ATTLIST pelicula id_pelicula ID #REQUIRED>
<!ATTLIST pelicula caratula CDATA #IMPLIED> 
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT actores (actor+)>
<!ELEMENT actor (nombre,apellido+)>
<!ELEMENT compras (dvds | cintas | (dvds,cintas))>
<!ELEMENT dvds (dvd+)>
<!ELEMENT dvd (extras?,titulo,fecha_salida_mercado)>
<!ELEMENT extras EMPTY>
<!ELEMENT fecha_salida_mercado (#PCDATA)>
<!ELEMENT cintas (cinta+)>
<!ELEMENT cinta (titulo,formato,rebobinado?)>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT rebobinado EMPTY>

=== salvatiti/2-DAW/XML/Videoclub/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "videoclub.dtd">
<facturas>
   <factura>
      <datos_cliente ident="c01">
	     <nombre>Antonio</nombre>
		 <apellido>Moreno</apellido>
		 <apellido>Flores</apellido>
		 <dni>123456789X</dni>
		 <tfno>916663322</tfno>
	  </datos_cliente>
	  
	  <datos_factura>
	     <resguardo>
		    <forma_pago>efectivo</forma_pago>
			<importe_total>35</importe_total>
		 </resguardo>
		 <alquileres>
		    <fecha>12/01/2007</fecha>
			<peliculas>
			   <pelicula id_pelicula="p320" caratula="foto_p0360">
			      <titulo>AQUELLAS JUERGAS UNIVERSITARIAS</titulo>
				  <genero>Comedia</genero>
				  <duracion>97min</duracion>
				  <actores>
				     <actor>
					    <nombre>Luke</nombre>
		                <apellido>Wilson</apellido>
		                <apellido>Peped</apellido>
					 </actor>
				     <actor>
					 	<nombre>Will</nombre>
		                <apellido>Farrel</apellido>
		                <apellido>Peped</apellido>
					 </actor>					 
				     <actor>
					 	<nombre>Vince</nombre>
		                <apellido>Vaughn</apellido>
		                <apellido>Pepe</apellido>
					 </actor>					 
				  </actores>
			    </pelicula>
			</peliculas>
		 </alquileres>
		 <compras>
		    <dvds>
			   <dvd>
			      <extras/>
				  <titulo>El oro de Moscú</titulo>
				  <fecha_salida_mercado>2006</fecha_salida_mercado>
			   </dvd>
			</dvds>
			<cintas>
			   <cinta>
			      <titulo>Gladiator</titulo>
				  <formato>VHS</formato>
			   </cinta>
			</cintas>
		 </compras>
	  </datos_factura>
   </factura>
</facturas>
